# Generated by Django 3.2.7 on 2021-12-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_alter_application_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application", old_name="address2", new_name="apt_number",
        ),
        migrations.RemoveField(model_name="application", name="address1",),
        migrations.AddField(
            model_name="application",
            name="street_address",
            field=models.CharField(
                default="", help_text="e.g. 35 St George St", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="conduct_agree",
            field=models.BooleanField(
                help_text='I have read and agree to the <a href="https://static.mlh.io/docs/mlh-code-of-conduct.pdf" rel="noopener noreferrer" target="_blank">MLH code of conduct</a>.'
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="logistics_agree",
            field=models.BooleanField(
                help_text='I authorize you to share my application/registration information with Major League Hackingfor event administration, ranking, and MLH administration in-line with the <a href="https://mlh.io/privacy" rel="noopener noreferrer" target="_blank">MLH Privacy Policy</a>. I further agree to the terms of both the <a href="https://github.com/MLH/mlh-policies/tree/master/prize-terms-and-conditions" rel="noopener noreferrer" target="_blank"> MLH Contest Terms and Conditions</a> and the <a href="https://mlh.io/privacy" rel="noopener noreferrer" target="_blank">MLH Privacy Policy.</a>'
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="referral_source",
            field=models.TextField(
                help_text="How did you hear about MakeUofT?", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="region",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="why_participate",
            field=models.TextField(
                help_text="Why do you want to participate in MakeUofT?", max_length=1000
            ),
        ),
    ]
