# Generated by Django 3.2.7 on 2021-12-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_auto_20211227_2343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="conduct_agree",
            field=models.BooleanField(
                help_text='I have read and agreed to the <a href="https://static.mlh.io/docs/mlh-code-of-conduct.pdf" rel="noopener noreferrer" target="_blank">MLH code of conduct</a>.'
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="logistics_agree",
            field=models.BooleanField(
                help_text='I authorize you to share my application/registration information with Major League Hacking for event administration, ranking, and MLH administration in-line with the <a href="https://mlh.io/privacy" rel="noopener noreferrer" target="_blank">MLH Privacy Policy</a>. I further agree to the terms of both the <a href="https://github.com/MLH/mlh-policies/tree/master/prize-terms-and-conditions" rel="noopener noreferrer" target="_blank"> MLH Contest Terms and Conditions</a> and the <a href="https://mlh.io/privacy" rel="noopener noreferrer" target="_blank">MLH Privacy Policy.</a>'
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="postal_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="street_address",
            field=models.CharField(
                blank=True, help_text="e.g. 35 St George St", max_length=255, null=True
            ),
        ),
    ]
